### ISSUE TITLE
Open source the site?

### ISSUE THREAD

**Issue by dan-giddins** [Crecket/masterypoints-placeholder#1]
Are you planning on releasing the source code of the site? I'd be grateful if you did!

It would be nice to be able to self-host the site, or maybe find some free hosting. Maybe others could get together and figure something out? Open-source projects can often find some kind of free hosting somewhere.

**Comment by Crecket** [comment]
The code base went from a tiny personal project with back then minimal dev experience, to what became the slow mess people experienced at the end. Anyone thinking of hosting a site like this is far better off starting from scratch and doing it properly with scale in mind 

There is also no "highscores" endpoint for the league API, all data had to be stored internally and was updated per person when they viewed a profile. That in turn means self hosting with a copy of my database would mean only your own data would update which seems a bit useless considering the main feature was that you could see where your position was in comparison to others
